#这里是zuul网关的配置
#忽略所有请求，不包括zuul.routes指定的路径
#zuul.ignored-services=*
# routes to serviceId 这里边是通过serviceid来绑定地址，当在路径后添加/api-a/   则是访问service-A对应的服务。
# ** 表示多层级，*表示单层级
#zuul:
#  routes:
#    api-a:
#      path: /match-jj/**
#      #这里用serviceId代替url，用服务名代替ip+端口号
#      serviceId: match-jj
#    api-b:
#      path: /match-hhs/**
#      #这里用serviceId代替url，用服务名代替ip+端口号
#      serviceId: match-hhs
